---
# tasks file for ansible-conntrackd
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: config_conntrackd.yml
  when: conntrackd_enable and conntrackd_config

- name: enable service
  service:
    name: conntrackd
    state: "{% if conntrackd_enable %}started{% else %}stopped{% endif %}"
    enabled: "{{ conntrackd_enable }}"